version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_db_golang_project
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  aux_container:
    container_name: aux_golang_container
    build: .
    volumes:
      - .:/app